// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNSg3mcOgBXkudJTdDxe5g7mpIEFfqvM',
    appId: '1:368846708150:web:8d45941420ef5f0c4e3517',
    messagingSenderId: '368846708150',
    projectId: 'totalxfirstrecriation',
    authDomain: 'totalxfirstrecriation.firebaseapp.com',
    storageBucket: 'totalxfirstrecriation.appspot.com',
    measurementId: 'G-7J98YJYZPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSbrmYq0gQvLH9xlZ0hw3J_BFKjizpWw',
    appId: '1:368846708150:android:75294e79f4caf9344e3517',
    messagingSenderId: '368846708150',
    projectId: 'totalxfirstrecriation',
    storageBucket: 'totalxfirstrecriation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTBcaMeVQ1YOOSCGVuxI1qx0RSrZfSgg',
    appId: '1:368846708150:ios:4786bd5c6e28d7f64e3517',
    messagingSenderId: '368846708150',
    projectId: 'totalxfirstrecriation',
    storageBucket: 'totalxfirstrecriation.appspot.com',
    androidClientId: '368846708150-t2cgtsfoi6ilotpmbdcdqpc0tgo98huh.apps.googleusercontent.com',
    iosClientId: '368846708150-tpi0m9o60bffgsn5bmmonil84uuojf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskSop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTBcaMeVQ1YOOSCGVuxI1qx0RSrZfSgg',
    appId: '1:368846708150:ios:4786bd5c6e28d7f64e3517',
    messagingSenderId: '368846708150',
    projectId: 'totalxfirstrecriation',
    storageBucket: 'totalxfirstrecriation.appspot.com',
    androidClientId: '368846708150-t2cgtsfoi6ilotpmbdcdqpc0tgo98huh.apps.googleusercontent.com',
    iosClientId: '368846708150-tpi0m9o60bffgsn5bmmonil84uuojf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskSop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxNSg3mcOgBXkudJTdDxe5g7mpIEFfqvM',
    appId: '1:368846708150:web:588cc40a739eddd84e3517',
    messagingSenderId: '368846708150',
    projectId: 'totalxfirstrecriation',
    authDomain: 'totalxfirstrecriation.firebaseapp.com',
    storageBucket: 'totalxfirstrecriation.appspot.com',
    measurementId: 'G-M1RF2J36NL',
  );
}
